id: f0f0d9ce7b49
kind: direct
title: New chat
created_by: horst.schwarz@joydev.com
created: 2026-07-18T12:45:49.281160413Z
updated: 2026-07-18T12:45:56.336654016Z
participants:
- horst.schwarz@joydev.com
messages: []
