id: a07044f229db
kind: direct
title: Vibe Test
created_by: horst.schwarz@joydev.com
created: 2026-07-18T12:44:13.111943915Z
updated: 2026-07-18T12:45:47.288120079Z
participants:
- horst.schwarz@joydev.com
- ai:vibe@joy
messages: []
