id: 7cf31881bb0e
kind: direct
title: New chat
created_by: horst.schwarz@joydev.com
created: 2026-07-12T21:11:04.118800185Z
updated: 2026-07-18T08:14:13.755390011Z
participants:
- horst.schwarz@joydev.com
messages: []
